### ISSUE TITLE
Request "latest-full" tag

### ISSUE THREAD

**Issue by douglascayers** [forcedotcom/salesforcedx-docker#15]
**Is your feature request related to a problem? Please describe.**

This request is related to tags on docker hub, https://hub.docker.com/r/salesforce/salesforcedx/tags

The "full" images are currently only tagged with a specific version, like 7.33.2-full, so I have to update my CI/CD scripts to use the latest versions of the full image. I would like to reference a tag that always uses the latest full image.

**Describe the solution you'd like**

I would like to reference a tag that always uses the latest full image. For example, "latest" refers to the latest slim image, it would be nice if "latest-full" referred to the latest full image.

**Describe alternatives you've considered**

Manually updating my CI/CD scripts when a new docker image is released, or install Salesforce CLI and tools explicitly in my script.

**Additional context**

![image](https://user-images.githubusercontent.com/4142577/69070330-ce7d6180-09dc-11ea-8b44-969ebfedcba5.png)

Error from CircleCI when trying to reference **salesforce/salesforcedx:latest-full**

![image](https://user-images.githubusercontent.com/4142577/69070388-e7861280-09dc-11ea-9266-412fdf6b8e74.png)

**Comment by douglascayers** [comment]
Hi @praksb, what are your thoughts on this request to have two `latest` tags in dockerhub so developers can grab the latest **slim** or **full** versions without needing to know the CLI version number? Thanks!

**Comment by praksb** [comment]
Hello @douglascayers Your request sounds reasonable to me. We will probably get to this only after the holidays. I'll update this thread once we make the change.

**Comment by douglascayers** [comment]
Thanks :)

**Comment by praksb** [comment]
@douglascayers This is now fixed. The next release would have the changes.

**Comment by douglascayers** [comment]
Thank you, @praksb!
