### ISSUE TITLE
Make JQ part of this image

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/salesforcedx-docker#19]
**Is your feature request related to a problem? Please describe.**
While working on our internal Bitbucket / SFDX CD (details here https://salesforce.stackexchange.com/q/293629/256) we stumbled over the need for JQ in the shellscripts that we call from the Pipeline. As JQ is not part of the standard salesforce docker image we have to install it on ever pipeline run. This makes it really slow and increases our costs for minutes on Bitbucket.

**Describe the solution you'd like**
If standard tools like JQ would be part of the image we could be more efficient.

**Describe alternatives you've considered**
Described above

**Comment by vazexqi** [comment]
@rsoesemann - See https://github.com/forcedotcom/salesforcedx-docker/issues/8#issuecomment-541897973

There should be two tags. Is the full tag not working for you?

**Comment by dieffrei** [comment]
For JQ use this tag: salesforce/salesforcedx:latest-full

**Comment by ntotten** [comment]
Per the other comments, use the full tag and jq is present.
