### ISSUE TITLE
Dockerhub has wrong versions

### ISSUE THREAD

**Issue by jhgihub0** [forcedotcom/salesforcedx-docker#25]
When I pull down https://hub.docker.com/r/salesforce/salesforcedx, it has the wrong versions installed, or its reporting it wrong with "sfdx version".  Please fix the docker hub versions.

docker pull salesforce/salesforcedx:latest-full
docker exec -it d3215bef4c35431fa14072410f65bab5bb5116bc40f3d14bbb09b79d67754828 /bin/sh; exit
> sfdx version
**sfdx-cli/7.82.0**-3d0c527ac6 linux-x64 node-v12.18.3

docker pull salesforce/salesforcedx:7.88.4-full
docker exec -it 2e725c40dcf3df1964620a1973a683d3c1e6da443733452305202cf06779be97 /bin/sh; exit
> sfdx version
**sfdx-cli/7.82.0**-3d0c527ac6 linux-x64 node-v12.18.3

docker pull salesforce/salesforcedx:7.86.3-full
docker exec -it 55db291d36cdb1d93488ace4b29dfbdc551986eeff552e70a1f0124b0809f2bd /bin/sh; exit
> sfdx version
**sfdx-cli/7.83.0**-eba9c6a927 linux-x64 node-v12.18.3

docker pull salesforce/salesforcedx:7.83.1-full
docker exec -it 90b440b7af1491491f1fb3e6f5d982f220c8691c5c663e0f7cfdbe1e784a723e /bin/sh; exit
> sfdx version
**sfdx-cli/7.83.0**-eba9c6a927 linux-x64 node-v12.18.3

Thank you.

**Comment by jhgihub0** [comment]
@jonnyhork @praksb seems this https://github.com/forcedotcom/salesforcedx-docker/blob/7.88.4/dockerfiles/Dockerfile_full#L15 is pulling down which 7.82.0 instead the correct version matching the branch

Seems this change was made as part of https://github.com/forcedotcom/salesforcedx-docker/commit/509417b25aebcaf4b9a97a0eb0060b3b4440f66d#diff-31ea40e7136443200c2829acddb5f6b98c3842d17eced9a0ba328b6b84be5207

**Comment by jonnyhork** [comment]
@jhgihub0 Thanks for bringing this to our attention. It looks like some internal changes have prevented the archives where we get the CLI from updating to the latest version. We will update our Dockerfiles in the next week or two once those changes should settle.

In the meantime, I will work on updating the images you pointed out to include the correct CLI version. 
Thanks for your patience!

**Comment by jhgihub0** [comment]
Great, thank you.

**Comment by jonnyhork** [comment]
@jhgihub0 I have updated the both the `latest-full` and `latest-slim` to contain the latest version of the CLI `7.89.2`.

Are you specifically using any of the other images with a later version? If not I will likely just delete those images.

Thanks

**Comment by jhgihub0** [comment]
Please update 7.86.1-full. Thank you

**Comment by jhgihub0** [comment]
Also, SFDX latest seems to have sfdx 7.36.0

<img width="589" alt="image" src="https://user-images.githubusercontent.com/59979805/109537133-904e6900-7a8c-11eb-9c84-11cebd02a739.png">

**Comment by jonnyhork** [comment]
Interesting, where are you building/running the image?

I just ran 
1. `docker pull salesforce/salesforcedx:latest-full`
2. ` docker run --rm -it  <image id>`
3. `sfdx`

<img width="1165" alt="Screen Shot 2021-03-01 at 10 56 21 AM" src="https://user-images.githubusercontent.com/25188632/109538249-1a8ed100-7a7d-11eb-84c0-96b45e25a8ba.png">

There may be a caching issue, can you try deleting any images and containers that you have previously built, then try the steps above?

**Comment by jhgihub0** [comment]
Please ignore my previous message, I pulled salesforce/salesforcedx:latest instead of salesforce/salesforcedx:latest-full.

Please update salesforce/salesforcedx:7.86.1-full

**Comment by jonnyhork** [comment]
@jhgihub0 `salesforce/salesforcedx:7.86.1-full` has been updated and published with cli version `7.86.1`. 
Hope that works for you!

Please let me know if you're having any other issues.

**Comment by jhgihub0** [comment]
That worked, thank you for your support

**Comment by jhgihub0** [comment]
Actually I think there is an issue with salesforce/salesforcedx:7.86.1-full

sfdx --version
sfdx plugins --core

Shows...


15:33:50  (node:210) Error Plugin: sfdx-cli: could not find package.json with {
15:33:50    type: 'dev',
15:33:50    root: '/usr/local/lib/nodejs/lib/node_modules/sfdx-cli',
15:33:50    name: '@oclif/plugin-command-snapshot'
15:33:50  }
15:33:50  module: @oclif/config@1.17.0
15:33:50  task: loadPlugins
15:33:50  plugin: sfdx-cli
15:33:50  root: /usr/local/lib/nodejs/lib/node_modules/sfdx-cli
15:33:50  See more details with DEBUG=*
15:33:50   ›   Warning: sfdx-cli update available from 7.86.1 to 7.89.2.
15:33:50  sfdx-cli/7.86.1 linux-x64 node-v12.18.2
15:33:50  

15:33:51  (node:225) Error Plugin: sfdx-cli: could not find package.json with {
15:33:51    type: 'dev',
15:33:51    root: '/usr/local/lib/nodejs/lib/node_modules/sfdx-cli',
15:33:51    name: '@oclif/plugin-command-snapshot'
15:33:51  }
15:33:51  module: @oclif/config@1.17.0
15:33:51  task: loadPlugins
15:33:51  plugin: sfdx-cli
15:33:51  root: /usr/local/lib/nodejs/lib/node_modules/sfdx-cli
15:33:51  See more details with DEBUG=*
15:33:52   ›   Warning: sfdx-cli update available from 7.86.1 to 7.89.2.
15:33:52  @oclif/plugin-autocomplete 0.1.5 (core)
15:33:52  @oclif/plugin-commands 1.3.0 (core)
15:33:52  @oclif/plugin-help 3.2.2 (core)
15:33:52  @oclif/plugin-not-found 1.2.4 (core)
15:33:52  @oclif/plugin-plugins 1.10.0 (core)
15:33:52  @oclif/plugin-update 1.3.10 (core)
15:33:52  @oclif/plugin-warn-if-update-available 1.7.0 (core)
15:33:52  @oclif/plugin-which 1.0.3 (core)
15:33:52  @salesforce/sfdx-trust 3.6.0 (core)
15:33:52  alias 1.1.5 (core)
15:33:52  analytics 1.12.1 (core)
15:33:52  auth 1.4.6 (core)
15:33:52  config 1.2.4 (core)
15:33:52  forcediff 0.0.1 (link) /home/jenkins/agent/workspace/DEMO2-SIT-monitor/sfdx_diff_package
15:33:52  generator 1.1.5 (core)
15:33:52  salesforcedx 50.16.1 (core)
15:33:52  ├─ limits 1.0.3 (core)
15:33:52  ├─ user 1.0.11 (core)
15:33:52  ├─ schema 1.0.3 (core)
15:33:52  ├─ custom-metadata 1.0.11 (core)
15:33:52  ├─ apex 0.1.4 (core)
15:33:52  ├─ templates 50.4.0 (core)
15:33:52  ├─ salesforce-alm 50.16.1 (core)
15:33:52  └─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
15:33:52  sfdx-cli 7.86.1 (core)
15:33:52  telemetry 1.0.1 (core)

**Comment by jonnyhork** [comment]
I am checking with our CLI team to verify, however I see the same error when I install `v7.86.1` outside of docker, locally on my machine, so it may be an issue with the version or some change to @oclif plugins since that version was released.

Is it possible for you to use a different image?

**Comment by jhgihub0** [comment]
7.89.2 works. Can you create a separate salesforce/salesforcedx:7.89.2-full ?

We pull down from docker and promote our artifacts in a custom way.  If I pull salesforce/salesforcedx:latest-full now, test it, and then try to promote it in a week or two, I might not get the same version.

**Comment by jonnyhork** [comment]
Sure, I have updated the image tagged `salesforce/salesforcedx:7.89.2-full` to have the correct CLI version installed.

Thanks.

**Comment by jhgihub0** [comment]
It seems to be working well, thank you.
