### ISSUE TITLE
 docker pull failing with default tag

### ISSUE THREAD

**Issue by karlgunst** [forcedotcom/salesforcedx-docker#34]
Running `docker pull salesforce/salesforcedx` or `docker pull salesforce/salesforcedx:latest` results in the error shown below

```
Error response from daemon: manifest for salesforce/salesforcedx:latest not found: 
manifest unknown: manifest unknown
```

This was working earlier today

**Comment by nedkov** [comment]
Also problem for us. Possible workaround https://salesforce.stackexchange.com/questions/354209/manifest-for-salesforce-salesforcedxlatest-not-found-manifest-unknown-manifes

**Comment by eugeneniemand** [comment]
Experiencing the same problem with latest/default just pinning to 7.113.0-full for now to continue working

**Comment by cristiand391** [comment]
Thanks for writing in, going to close this as duplicate of https://github.com/forcedotcom/cli/issues/1136.
