### ISSUE TITLE
Add jq to image

### ISSUE THREAD

**Issue by douglascayers** [forcedotcom/salesforcedx-docker#8]
**Is your feature request related to a problem? Please describe.**

I use Docker images in CI/CD pipelines. When scripting commands and reacting to the responses, I use the `--json` flag and parse the JSON with the [jq](https://stedolan.github.io/jq/) library.

A nice-to-have would be if the jq library were preloaded on this image so that I don't have to have a separate install step in my CI scripts.

**Describe the solution you'd like**

The jq library loaded as part of the [Dockerfile](https://github.com/forcedotcom/salesforcedx-docker/blob/master/Dockerfile) definition.

**Describe alternatives you've considered**

My CI scripts explicitly install jq.

```
apt update && apt -y install jq
```

**Additional context**

I first learned to use jq to parse CLI JSON responses by working with Wade Wegner on the [Salesforce Buildpack for Heroku](https://github.com/heroku/salesforce-buildpack/blob/master/bin/compile#L130)

**Comment by vazexqi** [comment]
The current proposal that we have is that we will have "slim" and "full" tags (exact name to be determined).

The "slim" one will have the baremetals to keep the image small. This should be the default if you were to just do a docker pull.

The "full" one will contain other utilities that are useful like jq, etc. We will rely on feedback on the community on what these are.

Thoughts?

**Comment by douglascayers** [comment]
Sounds like a great plan to me @vazexqi. I know that puts a bit more burden on you all to manage multiple Docker images, but from the end-user perspective, it gives more options **and** ability to still reference **officially supported** images before having to resort to (a) creating our own or (b) managing install steps in our CI scripts.

Thanks :)

**Comment by praksb** [comment]
@douglascayers This issue is now fixed. Our next release should have two docker images one with -full tag that contains jq and the CLI and the other one with -slim tag that contains only jq.

**Comment by douglascayers** [comment]
Thanks @praksb
